server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibermate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.amapping: orderConfirmation:com.facugl.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http://gateway-service:8222/api/v1/customers
    product-url: http://gateway-service:8222/api/v1/products
    payment-url: http://gateway-service:8222/api/v1/payments